// <auto-generated>
// YMM4 builds whose code was read as their differences from a read build, newest first: for each feature found
// to hold, the digest of its HostContracts parts (docs/HOST_CONTRACTS.md). Regenerate with
//   dotnet run --project tools/HostFingerprint -- reviewed NVEncVideoWriterPlugin/HostReviewedBuilds.cs <version>=<YMM4 dir>@<feature>,...
// giving every reviewed build (also after changing HostContracts.Rules).
// </auto-generated>
namespace NVEncVideoWriterPlugin;

internal static partial class HostContracts
{
    internal static readonly ReviewedBuild[] Reviewed =
    [
        new("4.56.0.0〜4.56.0.1", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "170B8F83EA90726768743F57B30C9418",
            ["preview"] = "E75AC3E383AA54D9CAF476C9F3D43A7A",
            ["selection-rects"] = "C8C6C39B19B1549D7D6B4FA0D359DF93",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "683BF79270C5E8EEE093BA4F88BB5CF4",
            ["identity-random"] = "4CC9C8091176449F1E982B5A2C203D34",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.FFmpeg"] = "064F0C88EBD0467276584E33C2B55178",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "5BD1CC053725774267ACF0E50F95805D",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "F78D984A3FF2579D6F0A9FA80B115E42",
        }),
        new("4.55.1.1", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "37BA8409BE8CDF2912C781C26CB50FFB",
            ["preview"] = "1C5834CB24954511F06B798223301979",
            ["selection-rects"] = "6E59CB2B6BA30ECAD96C5EE95E0A2C8F",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "539B25AB83003DED12F749BE4F8C5612",
            ["identity-random"] = "C72B28CFF339B4F2E275ACF1B42CE8BA",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.FFmpeg"] = "FF602E3ECA6733B7A648788152BADD1B",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "B561D9FAD990EB57ABFF614F02A811A9",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "7C2A96A5FD7BF05CEEEDAAAE63CB55C8",
        }),
        new("4.55.1.0", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "1D524BDFA6DB0651CFE91B332E910969",
            ["preview"] = "1C5834CB24954511F06B798223301979",
            ["selection-rects"] = "ADCA0F991926610BD923D8C8C99C3A66",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "539B25AB83003DED12F749BE4F8C5612",
            ["identity-random"] = "C72B28CFF339B4F2E275ACF1B42CE8BA",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.FFmpeg"] = "FF602E3ECA6733B7A648788152BADD1B",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "B561D9FAD990EB57ABFF614F02A811A9",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "7C2A96A5FD7BF05CEEEDAAAE63CB55C8",
        }),
        new("4.55.0.0〜4.55.0.1", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "6D8943EC6FC56BB7C24F7EBD49B3976C",
            ["preview"] = "5F7B7D54E1F9294BA930C682CFB6F52E",
            ["selection-rects"] = "20F306EDA713BE00F9D0F36D6A0A9BD0",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "539B25AB83003DED12F749BE4F8C5612",
            ["identity-random"] = "31140C1835B3ADA9EFDC87D7EFD05092",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.FFmpeg"] = "FF602E3ECA6733B7A648788152BADD1B",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "B561D9FAD990EB57ABFF614F02A811A9",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "7C2A96A5FD7BF05CEEEDAAAE63CB55C8",
        }),
        new("4.54.0.1", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "12C24438D748022353684E1631936F04",
            ["preview"] = "755A786EDF58560BD899EE08E8E23D20",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "539B25AB83003DED12F749BE4F8C5612",
            ["identity-random"] = "FEFD5E1512122C91974F8D253E26AF15",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.FFmpeg"] = "FF602E3ECA6733B7A648788152BADD1B",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "033C00F0E8B2F7168266662A3DB7D0F1",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "7C2A96A5FD7BF05CEEEDAAAE63CB55C8",
        }),
        new("4.54.0.0", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "3433DDFCACE5E3802F3B22888AE24168",
            ["preview"] = "755A786EDF58560BD899EE08E8E23D20",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "539B25AB83003DED12F749BE4F8C5612",
            ["identity-random"] = "7A236161A82D893319CF1F1C5CBD1BFF",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "F9209DC72FB36083873B84381EBFA721",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "7C2A96A5FD7BF05CEEEDAAAE63CB55C8",
        }),
        new("4.53.0.9", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "4165722F25A7824ED00A32C710A7A863",
            ["preview"] = "755A786EDF58560BD899EE08E8E23D20",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "539B25AB83003DED12F749BE4F8C5612",
            ["identity-random"] = "7A236161A82D893319CF1F1C5CBD1BFF",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "F9209DC72FB36083873B84381EBFA721",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "7C2A96A5FD7BF05CEEEDAAAE63CB55C8",
        }),
        new("4.53.0.7〜4.53.0.8", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "79F15F2F5A42D1B9B17578F71C1A688A",
            ["preview"] = "755A786EDF58560BD899EE08E8E23D20",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "539B25AB83003DED12F749BE4F8C5612",
            ["identity-random"] = "7A236161A82D893319CF1F1C5CBD1BFF",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "F9209DC72FB36083873B84381EBFA721",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "7C2A96A5FD7BF05CEEEDAAAE63CB55C8",
        }),
        new("4.53.0.6", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "D554ADD4E55815867FE5D244FDF25E60",
            ["preview"] = "60AB7263BFF647BA3927E6973DF02B96",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "539B25AB83003DED12F749BE4F8C5612",
            ["identity-random"] = "D8E5E0350AF45C120A93A8281CCE56B4",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "BD70214817CD7ADDC9C60EA7009415B2",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "7C2A96A5FD7BF05CEEEDAAAE63CB55C8",
        }),
        new("4.53.0.5", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "CCEC335D423530E3BF27F427C3631A45",
            ["preview"] = "CEAD709A1CDBCB6109DC8C3743BAAB37",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "539B25AB83003DED12F749BE4F8C5612",
            ["identity-random"] = "553C5718A691DCFD038697FA6F08A979",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "E9DACA08BCEE3C2D565D94678FC17BF0",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "7C2A96A5FD7BF05CEEEDAAAE63CB55C8",
        }),
        new("4.53.0.4", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "D4C234F2D90843AD2E16F0BFEBE54CEE",
            ["preview"] = "CEAD709A1CDBCB6109DC8C3743BAAB37",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "539B25AB83003DED12F749BE4F8C5612",
            ["identity-random"] = "FCDA2A71C661CD81E7C3B6AB242C9FAF",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "7164D9DB09F7606A3D4EB69141594985",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "7C2A96A5FD7BF05CEEEDAAAE63CB55C8",
        }),
        new("4.53.0.3", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "32DB6E13C091810C48FBB3717CB5FE64",
            ["preview"] = "CEAD709A1CDBCB6109DC8C3743BAAB37",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "539B25AB83003DED12F749BE4F8C5612",
            ["identity-random"] = "7CE9803155709293494EB9EA1D331135",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "ECA1C86B8072AE5FFA29200A4211C7ED",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "7C2A96A5FD7BF05CEEEDAAAE63CB55C8",
        }),
        new("4.53.0.2", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "779BF5361B88E80808FE43157A5089C2",
            ["preview"] = "34E071D80153BFC2315BA2A87A3528FD",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "EAD75D41DB94C6EDA0F2BD0A235EF7BB",
            ["identity-random"] = "7CE9803155709293494EB9EA1D331135",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "1F5ACEC9F2DBF57E17196D384E5D8CC4",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "7C2A96A5FD7BF05CEEEDAAAE63CB55C8",
        }),
        new("4.53.0.1", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "B8109422D6688A10ABCE8B64965FD3C7",
            ["preview"] = "84D2FEAF4E02EF99C26784E8C141BA0D",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "EAD75D41DB94C6EDA0F2BD0A235EF7BB",
            ["identity-random"] = "5965612A1D579A3C264AC1722D2B9F0C",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "65B526BE675732B0677D28A643CF237B",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "7C2A96A5FD7BF05CEEEDAAAE63CB55C8",
        }),
        new("4.53.0.0", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "B8109422D6688A10ABCE8B64965FD3C7",
            ["preview"] = "84D2FEAF4E02EF99C26784E8C141BA0D",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "EAD75D41DB94C6EDA0F2BD0A235EF7BB",
            ["identity-random"] = "5965612A1D579A3C264AC1722D2B9F0C",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "2C89B9D73F8443ED20DECF7A57232FCA",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "7C2A96A5FD7BF05CEEEDAAAE63CB55C8",
        }),
        new("4.52.0.8", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "154C53C4732CB214BD6BB079C532EC8C",
            ["preview"] = "84D2FEAF4E02EF99C26784E8C141BA0D",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "EAD75D41DB94C6EDA0F2BD0A235EF7BB",
            ["identity-random"] = "10901A14E8F831D120299D95DCE86A28",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "5972BD6FC068A2D733490A6AA1ADC548",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "7C2A96A5FD7BF05CEEEDAAAE63CB55C8",
        }),
        new("4.52.0.6〜4.52.0.7", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "154C53C4732CB214BD6BB079C532EC8C",
            ["preview"] = "84D2FEAF4E02EF99C26784E8C141BA0D",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "EAD75D41DB94C6EDA0F2BD0A235EF7BB",
            ["identity-random"] = "10901A14E8F831D120299D95DCE86A28",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "6269A7502F5B30C598CD3CAC413565D6",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "7C2A96A5FD7BF05CEEEDAAAE63CB55C8",
        }),
        new("4.52.0.3〜4.52.0.5", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "154C53C4732CB214BD6BB079C532EC8C",
            ["preview"] = "84D2FEAF4E02EF99C26784E8C141BA0D",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "EAD75D41DB94C6EDA0F2BD0A235EF7BB",
            ["identity-random"] = "80C5B61EAC335A7161C938080A81BFBF",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "6269A7502F5B30C598CD3CAC413565D6",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "7C2A96A5FD7BF05CEEEDAAAE63CB55C8",
        }),
        new("4.52.0.2", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "154C53C4732CB214BD6BB079C532EC8C",
            ["preview"] = "84D2FEAF4E02EF99C26784E8C141BA0D",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "EAD75D41DB94C6EDA0F2BD0A235EF7BB",
            ["identity-random"] = "0C139ED7D9FC1C5C13FFDEF89B5F223C",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "6269A7502F5B30C598CD3CAC413565D6",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "7C2A96A5FD7BF05CEEEDAAAE63CB55C8",
        }),
        new("4.52.0.0〜4.52.0.1", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "154C53C4732CB214BD6BB079C532EC8C",
            ["preview"] = "537A7EDC13ED2FF69421F6F4B05187CC",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "EAD75D41DB94C6EDA0F2BD0A235EF7BB",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "6269A7502F5B30C598CD3CAC413565D6",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "7C2A96A5FD7BF05CEEEDAAAE63CB55C8",
        }),
        new("4.51.0.3", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "2D3024780237E6450CE26454192A0EFE",
            ["preview"] = "537A7EDC13ED2FF69421F6F4B05187CC",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "D9403EE844D8B20DB57D6B14DDF4DDD5",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "02747E859D4A1015FE5F8BDA16BB2844",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "6DDA048FBEB40ADF4EC25BA5697560BD",
        }),
        new("4.51.0.2", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "ACEA79D01F286E36881676105A83B3C9",
            ["preview"] = "537A7EDC13ED2FF69421F6F4B05187CC",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "D9403EE844D8B20DB57D6B14DDF4DDD5",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "02747E859D4A1015FE5F8BDA16BB2844",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "6DDA048FBEB40ADF4EC25BA5697560BD",
        }),
        new("4.51.0.0〜4.51.0.1", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "5978EB4D302759B494094826A057A333",
            ["preview"] = "537A7EDC13ED2FF69421F6F4B05187CC",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "D9403EE844D8B20DB57D6B14DDF4DDD5",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "02747E859D4A1015FE5F8BDA16BB2844",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "6DDA048FBEB40ADF4EC25BA5697560BD",
        }),
        new("4.50.0.3", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "197B16E483F91F66364F4E4BFAFE6DA9",
            ["preview"] = "537A7EDC13ED2FF69421F6F4B05187CC",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "D9403EE844D8B20DB57D6B14DDF4DDD5",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "1C3775E7C1761ECA75FA460068501160",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "6DDA048FBEB40ADF4EC25BA5697560BD",
        }),
        new("4.50.0.1〜4.50.0.2", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "9E4F17EFD24CC435390FF2C0B436D01D",
            ["preview"] = "537A7EDC13ED2FF69421F6F4B05187CC",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "D9403EE844D8B20DB57D6B14DDF4DDD5",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "1C3775E7C1761ECA75FA460068501160",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "6DDA048FBEB40ADF4EC25BA5697560BD",
        }),
        new("4.50.0.0", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "1D16F2A646BD682BB306AEE26A440E06",
            ["preview"] = "537A7EDC13ED2FF69421F6F4B05187CC",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "D9403EE844D8B20DB57D6B14DDF4DDD5",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "1C3775E7C1761ECA75FA460068501160",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "6DDA048FBEB40ADF4EC25BA5697560BD",
        }),
        new("4.49.0.0〜4.49.1.0", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "EE1E1535B54C77CCF413E8CDE36D87B4",
            ["preview"] = "537A7EDC13ED2FF69421F6F4B05187CC",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "D9403EE844D8B20DB57D6B14DDF4DDD5",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "1C3775E7C1761ECA75FA460068501160",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "6DDA048FBEB40ADF4EC25BA5697560BD",
        }),
        new("4.48.1.2", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "5C126C00785BA7FBB980D846CECCB7FE",
            ["preview"] = "537A7EDC13ED2FF69421F6F4B05187CC",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "D9403EE844D8B20DB57D6B14DDF4DDD5",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "47EA710C56142C9B3347ECE95C8DBDC9",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "6DDA048FBEB40ADF4EC25BA5697560BD",
        }),
        new("4.48.1.1", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "5C126C00785BA7FBB980D846CECCB7FE",
            ["preview"] = "537A7EDC13ED2FF69421F6F4B05187CC",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "D9403EE844D8B20DB57D6B14DDF4DDD5",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "B5775AE57A9989EDBD0A985F5CE42A53",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "6DDA048FBEB40ADF4EC25BA5697560BD",
        }),
        new("4.48.1.0", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "5C126C00785BA7FBB980D846CECCB7FE",
            ["preview"] = "537A7EDC13ED2FF69421F6F4B05187CC",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "D9403EE844D8B20DB57D6B14DDF4DDD5",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "C45068272C31C8F3311A262C717E8C5B",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "6DDA048FBEB40ADF4EC25BA5697560BD",
        }),
        new("4.48.0.5", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "FA810D4B00FB8D070A2F3A359C525C04",
            ["preview"] = "03A151C40BE0CF25B548806B96976A49",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "D9403EE844D8B20DB57D6B14DDF4DDD5",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "5649E9A8B5F49799257052350F9D4E07",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "6DDA048FBEB40ADF4EC25BA5697560BD",
        }),
        new("4.48.0.4", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "FA810D4B00FB8D070A2F3A359C525C04",
            ["preview"] = "03A151C40BE0CF25B548806B96976A49",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "D9403EE844D8B20DB57D6B14DDF4DDD5",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "77AB89448575661628EE9202D64F2CA6",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "6DDA048FBEB40ADF4EC25BA5697560BD",
        }),
        new("4.48.0.3", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "FA810D4B00FB8D070A2F3A359C525C04",
            ["preview"] = "03A151C40BE0CF25B548806B96976A49",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "D9403EE844D8B20DB57D6B14DDF4DDD5",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "3CBAE06B732583ACAA0EC42042C29804",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "6DDA048FBEB40ADF4EC25BA5697560BD",
        }),
        new("4.48.0.2", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "FA810D4B00FB8D070A2F3A359C525C04",
            ["preview"] = "03A151C40BE0CF25B548806B96976A49",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "D9403EE844D8B20DB57D6B14DDF4DDD5",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "F7D0F7FB262C47799D41271DEE536FB2",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "6DDA048FBEB40ADF4EC25BA5697560BD",
        }),
        new("4.48.0.0〜4.48.0.1", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "FA810D4B00FB8D070A2F3A359C525C04",
            ["preview"] = "03A151C40BE0CF25B548806B96976A49",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "D9403EE844D8B20DB57D6B14DDF4DDD5",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "636963A96CABE9CC6538486BCB2E6153",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "6DDA048FBEB40ADF4EC25BA5697560BD",
        }),
        new("4.47.0.0〜4.47.0.5", new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["core"] = "8B32F09DD3121B8C3A7DEE178DF43DAD",
            ["preview"] = "03A151C40BE0CF25B548806B96976A49",
            ["wrapped-sources"] = "0D80927F28BD6DFE9EC4DC3F2B24DFBF",
            ["ruler-bars"] = "D9403EE844D8B20DB57D6B14DDF4DDD5",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.MediaFoundation"] = "8C087C057B1C1F7C4D90A0F1DBC7A022",
            ["decoder:YukkuriMovieMaker.Plugin.FileSource.WIC"] = "6DDA048FBEB40ADF4EC25BA5697560BD",
        }),
    ];
}
